package in.petsfort.crm;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.jay.rpc.RpcException;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

final class ReportingService {
    private final CrmDatabase database;
    ReportingService(CrmDatabase database) { this.database = database; }

    JsonObject gstDashboard(String fy) throws SQLException, RpcException {
        Range range = financialYear(fy); JsonArray rows = database.query("SELECT o.order_id,o.created_at,o.total,o.order_status,b.bill,u.name user_name FROM orders o LEFT JOIN bills b ON o.order_id=b.order_id LEFT JOIN userdata u ON o.user_id=u.uid OR o.user_id=u.id WHERE o.created_at>=? AND o.created_at<=? ORDER BY o.created_at", List.of(range.fromIso(), range.toIso()));
        BigDecimal taxable = Money.ZERO, cgst = Money.ZERO, sgst = Money.ZERO, invoiced = Money.ZERO; int count = 0; Map<String, Totals> monthly = new LinkedHashMap<>();
        for (JsonElement element : rows) { JsonObject row = element.getAsJsonObject(), bill = bill(row); if (bill == null) continue; JsonObject totals = bill.has("totals") ? bill.getAsJsonObject("totals") : new JsonObject();
            BigDecimal sub = Money.of(totals, "subTotal"), c = Money.of(totals, "cgstAmount"), s = Money.of(totals, "sgstAmount"), total = Money.of(totals, "total");
            taxable=taxable.add(sub); cgst=cgst.add(c); sgst=sgst.add(s); invoiced=invoiced.add(total); count++;
            String month = text(row,"created_at",""); if (month.length()>=7) monthly.computeIfAbsent(month.substring(0,7), ignored->new Totals()).add(sub,c,s,total); }
        JsonObject cn = database.one("SELECT COUNT(*) count,COALESCE(SUM(total),0) total,COALESCE(SUM(cgst_total),0) cgst,COALESCE(SUM(sgst_total),0) sgst FROM credit_notes WHERE created_at>=? AND created_at<=?", List.of(range.fromIso(),range.toIso()));
        JsonObject dn = database.one("SELECT COUNT(*) count,COALESCE(SUM(total),0) total,COALESCE(SUM(cgst_total),0) cgst,COALESCE(SUM(sgst_total),0) sgst FROM debit_notes WHERE created_at>=? AND created_at<=?", List.of(range.fromIso(),range.toIso()));
        JsonObject out=new JsonObject(); out.addProperty("fy",fy==null?"current":fy); out.addProperty("fy_start",range.from); out.addProperty("fy_end",range.to);
        money(out,"total_taxable",taxable); money(out,"total_cgst",cgst); money(out,"total_sgst",sgst); money(out,"total_tax",cgst.add(sgst)); money(out,"total_invoiced",invoiced); out.addProperty("invoice_count",count);
        out.addProperty("credit_note_count",cn.get("count").getAsLong()); money(out,"credit_note_total",Money.of(cn,"total")); out.addProperty("debit_note_count",dn.get("count").getAsLong()); money(out,"debit_note_total",Money.of(dn,"total"));
        money(out,"net_tax_liability",cgst.add(sgst).subtract(Money.of(cn,"cgst")).subtract(Money.of(cn,"sgst")).add(Money.of(dn,"cgst")).add(Money.of(dn,"sgst")));
        JsonObject months=new JsonObject(); monthly.forEach((key,value)->months.add(key,value.json())); out.add("monthly",months); return out;
    }

    JsonArray salesRegister(String from, String to) throws SQLException, RpcException {
        requireDates(from,to); JsonArray rows=database.query("SELECT o.order_id,o.user_id,o.created_at,o.total,o.order_status,b.bill,u.name user_name,u.gstin user_gstin FROM orders o LEFT JOIN bills b ON o.order_id=b.order_id LEFT JOIN userdata u ON o.user_id=u.uid OR o.user_id=u.id WHERE o.created_at>=? AND o.created_at<=? ORDER BY o.created_at DESC",List.of(from+"T00:00:00",to+"T23:59:59")); JsonArray result=new JsonArray();
        for(JsonElement element:rows){JsonObject r=element.getAsJsonObject(),b=bill(r),e=new JsonObject(); e.addProperty("order_id",text(r,"order_id",""));e.addProperty("date",text(r,"created_at",""));e.addProperty("invoice_no","");e.addProperty("party_name",text(r,"user_name",""));e.addProperty("gstin",text(r,"user_gstin",""));money(e,"taxable_value",Money.ZERO);money(e,"cgst",Money.ZERO);money(e,"sgst",Money.ZERO);money(e,"total",Money.of(r,"total"));e.addProperty("order_status",text(r,"order_status",""));e.add("items",new JsonArray());e.add("gst_details",new JsonArray());
            if(b!=null){JsonObject t=b.getAsJsonObject("totals");e.addProperty("invoice_no",text(b.getAsJsonObject("details"),"invoiceNo",""));money(e,"taxable_value",Money.of(t,"subTotal"));money(e,"cgst",Money.of(t,"cgstAmount"));money(e,"sgst",Money.of(t,"sgstAmount"));money(e,"total",Money.of(t,"total"));e.add("items",b.getAsJsonArray("items").deepCopy());e.add("gst_details",b.getAsJsonArray("gstDetails").deepCopy());JsonObject buyer=b.getAsJsonObject("buyer");if(buyer!=null&&!text(buyer,"gstin","").isBlank())e.addProperty("gstin",text(buyer,"gstin",""));}result.add(e);}return result;
    }

    JsonObject partyLedger(String from,String to,String userId)throws SQLException,RpcException{requireDates(from,to);String filter=userId==null?"":" AND o.user_id=?";List<Object>p=new ArrayList<>(List.of(from+"T00:00:00",to+"T23:59:59"));if(userId!=null)p.add(userId);JsonArray entries=new JsonArray();
        for(JsonElement x:database.query("SELECT o.order_id,o.user_id,o.created_at,o.total,o.order_status,u.name user_name FROM orders o LEFT JOIN userdata u ON o.user_id=u.uid OR o.user_id=u.id WHERE o.created_at>=? AND o.created_at<=?"+filter+" ORDER BY o.created_at",p))entries.add(ledger(x.getAsJsonObject(),"Sale","INV-"+text(x.getAsJsonObject(),"order_id",""),Money.of(x.getAsJsonObject(),"total"),Money.ZERO));
        addNoteLedger(entries,"credit_notes","cn_number","Credit Note",from,to,userId,false);addNoteLedger(entries,"debit_notes","dn_number","Debit Note",from,to,userId,true);sort(entries,"date");BigDecimal debit=Money.ZERO,credit=Money.ZERO;for(JsonElement x:entries){debit=debit.add(Money.of(x.getAsJsonObject(),"debit"));credit=credit.add(Money.of(x.getAsJsonObject(),"credit"));}JsonObject out=new JsonObject();out.add("entries",entries);money(out,"total_debit",debit);money(out,"total_credit",credit);money(out,"net_balance",debit.subtract(credit));return out;}

    JsonObject dayBook(String from,String to)throws SQLException,RpcException{requireDates(from,to);JsonArray entries=new JsonArray();
        for(JsonElement x:database.query("SELECT o.order_id,o.user_id,o.created_at,o.total,o.total_rate,o.total_gst,o.total_discount,o.order_status,b.bill,u.name user_name FROM orders o LEFT JOIN bills b ON o.order_id=b.order_id LEFT JOIN userdata u ON o.user_id=u.uid OR o.user_id=u.id WHERE o.created_at>=? AND o.created_at<=? ORDER BY o.created_at",List.of(from+"T00:00:00",to+"T23:59:59"))){JsonObject r=x.getAsJsonObject(),b=bill(r),e=new JsonObject();e.addProperty("date",text(r,"created_at",""));e.addProperty("type","Sales");e.addProperty("voucher_no",b==null?"INV-"+text(r,"order_id",""):text(b.getAsJsonObject("details"),"invoiceNo","INV-"+text(r,"order_id","")));e.addProperty("party",text(r,"user_name",text(r,"user_id","")));money(e,"amount",Money.of(r,"total"));money(e,"taxable",Money.of(r,"total_rate"));money(e,"tax",Money.of(r,"total_gst"));e.addProperty("status",text(r,"order_status",""));e.addProperty("order_id",text(r,"order_id",""));entries.add(e);}
        addDayNotes(entries,"credit_notes","cn_number","Credit Note",from,to);addDayNotes(entries,"debit_notes","dn_number","Debit Note",from,to);sort(entries,"date");BigDecimal sales=Money.ZERO,cn=Money.ZERO,dn=Money.ZERO;int sc=0,cc=0,dc=0;for(JsonElement x:entries){JsonObject e=x.getAsJsonObject();switch(text(e,"type","")){case"Sales":sales=sales.add(Money.of(e,"amount"));sc++;break;case"Credit Note":cn=cn.add(Money.of(e,"amount"));cc++;break;default:dn=dn.add(Money.of(e,"amount"));dc++;}}JsonObject s=new JsonObject();s.addProperty("total_entries",entries.size());s.addProperty("sales_count",sc);s.addProperty("cn_count",cc);s.addProperty("dn_count",dc);money(s,"total_sales",sales);money(s,"total_cn",cn);money(s,"total_dn",dn);money(s,"net_amount",sales.subtract(cn).add(dn));JsonObject out=new JsonObject();out.add("entries",entries);out.add("summary",s);return out;}

    JsonObject profitLoss(String fy)throws SQLException,RpcException{Range range=financialYear(fy);JsonArray rows=database.query("SELECT o.order_id,o.total,o.total_rate,o.total_gst,o.total_discount,o.order_status,o.created_at,b.bill FROM orders o LEFT JOIN bills b ON o.order_id=b.order_id WHERE o.created_at>=? AND o.created_at<=?",List.of(range.fromIso(),range.toIso()));BigDecimal revenue=Money.ZERO,taxable=Money.ZERO,cgst=Money.ZERO,sgst=Money.ZERO,mrp=Money.ZERO,discount=Money.ZERO,cancelled=Money.ZERO;int cancelledCount=0;Map<String,Totals>monthly=new LinkedHashMap<>();
        for(JsonElement x:rows){JsonObject r=x.getAsJsonObject();if("ORDER_CANCELLED".equals(text(r,"order_status",""))){cancelledCount++;cancelled=cancelled.add(Money.of(r,"total"));continue;}JsonObject b=bill(r);revenue=revenue.add(Money.of(r,"total"));taxable=taxable.add(Money.of(r,"total_rate"));discount=discount.add(Money.of(r,"total_discount"));if(b!=null){JsonObject t=b.getAsJsonObject("totals");cgst=cgst.add(Money.of(t,"cgstAmount"));sgst=sgst.add(Money.of(t,"sgstAmount"));for(JsonElement item:b.getAsJsonArray("items")){JsonObject i=item.getAsJsonObject();mrp=mrp.add(Money.of(i,"mrp").multiply(BigDecimal.valueOf(digits(text(i,"quantityBilled","0")))));}}else{BigDecimal half=Money.of(r,"total_gst").divide(new BigDecimal("2"),12,Money.ROUNDING);cgst=cgst.add(half);sgst=sgst.add(half);}String month=text(r,"created_at","");if(month.length()>=7)monthly.computeIfAbsent(month.substring(0,7),k->new Totals()).add(Money.of(r,"total_rate"),Money.of(r,"total_gst").divide(new BigDecimal("2"),12,Money.ROUNDING),Money.of(r,"total_gst").divide(new BigDecimal("2"),12,Money.ROUNDING),Money.of(r,"total"));}
        JsonObject cn=noteTotals("credit_notes",range),dn=noteTotals("debit_notes",range);BigDecimal tax=cgst.add(sgst);JsonObject out=new JsonObject();out.addProperty("fy",fy==null?"current":fy);JsonObject rev=new JsonObject();money(rev,"gross_sales_mrp",mrp);money(rev,"discount_given",discount);money(rev,"net_sales_taxable",taxable);money(rev,"cgst_collected",cgst);money(rev,"sgst_collected",sgst);money(rev,"total_tax_collected",tax);money(rev,"total_revenue",revenue);money(rev,"credit_note_adj",Money.of(cn,"total"));money(rev,"debit_note_adj",Money.of(dn,"total"));money(rev,"net_revenue",revenue.subtract(Money.of(cn,"total")).add(Money.of(dn,"total")));out.add("revenue",rev);
        JsonObject orders=new JsonObject();orders.addProperty("total_orders",rows.size());orders.addProperty("active_orders",rows.size()-cancelledCount);orders.addProperty("cancelled_orders",cancelledCount);money(orders,"cancelled_value",cancelled);out.add("orders",orders);JsonObject profitability=new JsonObject();money(profitability,"gross_mrp_value",mrp);money(profitability,"discount_given",discount);money(profitability,"effective_selling_price",taxable);BigDecimal margin=mrp.subtract(taxable);money(profitability,"margin_on_mrp",mrp.signum()>0?margin:Money.ZERO);money(profitability,"margin_percentage",mrp.signum()>0?margin.multiply(Money.HUNDRED).divide(mrp,12,Money.ROUNDING):Money.ZERO);out.add("profitability",profitability);
        JsonObject taxes=new JsonObject();money(taxes,"output_cgst",cgst);money(taxes,"output_sgst",sgst);money(taxes,"total_output_tax",tax);BigDecimal cnTax=Money.of(cn,"cgst").add(Money.of(cn,"sgst")),dnTax=Money.of(dn,"cgst").add(Money.of(dn,"sgst"));money(taxes,"cn_tax_adj",cnTax);money(taxes,"dn_tax_adj",dnTax);money(taxes,"net_tax_payable",tax.subtract(cnTax).add(dnTax));out.add("tax_summary",taxes);JsonObject months=new JsonObject();monthly.forEach((k,v)->months.add(k,v.json()));out.add("monthly",months);return out;}

    JsonObject stockSummary()throws SQLException{JsonArray rows=database.query("SELECT p.id,p.product_id,p.product_name,p.product_hsn,p.product_cid,p.cost_mrp,p.cost_rate,p.cost_gst,p.cost_dis,p.stock,c.name category_name FROM products p LEFT JOIN category c ON p.cat_id=c.id ORDER BY p.product_name",List.of());JsonArray products=new JsonArray();BigDecimal stockValue=Money.ZERO,mrpValue=Money.ZERO;long units=0;int oos=0,low=0;Map<String,Category>categories=new LinkedHashMap<>();for(JsonElement x:rows){JsonObject r=x.getAsJsonObject();int stock=r.get("stock").getAsInt();BigDecimal mrp=Money.of(r,"cost_mrp"),rate=Money.rateAfterDiscount(mrp,Money.of(r,"cost_dis")),sv=rate.multiply(BigDecimal.valueOf(stock)),mv=mrp.multiply(BigDecimal.valueOf(stock));stockValue=stockValue.add(sv);mrpValue=mrpValue.add(mv);units+=stock;if(stock==0)oos++;else if(stock<5)low++;String cat=text(r,"category_name","Uncategorized");categories.computeIfAbsent(cat,k->new Category()).add(stock,sv);JsonObject p=new JsonObject();p.addProperty("id",text(r,"id",""));p.addProperty("product_id",text(r,"product_id",""));p.addProperty("name",text(r,"product_name",""));p.addProperty("hsn",text(r,"product_hsn",""));p.addProperty("category",cat);money(p,"mrp",mrp);money(p,"rate",rate);p.addProperty("gst_pct",Money.of(r,"cost_gst"));p.addProperty("discount_pct",Money.of(r,"cost_dis"));p.addProperty("stock",stock);money(p,"stock_value",sv);money(p,"mrp_value",mv);products.add(p);}JsonObject summary=new JsonObject();summary.addProperty("total_products",products.size());summary.addProperty("total_items",units);money(summary,"total_stock_value",stockValue);money(summary,"total_mrp_value",mrpValue);summary.addProperty("out_of_stock",oos);summary.addProperty("low_stock",low);JsonObject cats=new JsonObject();categories.forEach((k,v)->cats.add(k,v.json()));JsonObject out=new JsonObject();out.add("products",products);out.add("summary",summary);out.add("category_summary",cats);return out;}

    JsonObject outstanding()throws SQLException{JsonArray rows=database.query("SELECT u.uid,u.name,u.email,u.contact,u.gstin,u.credits,COUNT(o.order_id) total_orders,COALESCE(SUM(CASE WHEN o.order_status!='ORDER_CANCELLED' THEN o.total ELSE 0 END),0) total_purchased,MAX(o.created_at) last_order_date FROM userdata u LEFT JOIN orders o ON u.uid=o.user_id OR u.id=o.user_id GROUP BY u.uid ORDER BY u.credits DESC",List.of());JsonArray parties=new JsonArray();BigDecimal credits=Money.ZERO,outstanding=Money.ZERO;int withCredit=0,withDues=0;for(JsonElement x:rows){JsonObject r=x.getAsJsonObject(),p=new JsonObject();BigDecimal c=Money.of(r,"credits");credits=credits.add(c);if(c.signum()<0){outstanding=outstanding.add(c.abs());withDues++;}if(c.signum()>0)withCredit++;for(String f:List.of("uid","name","email","contact","gstin"))p.addProperty(f,text(r,f,""));money(p,"credits",c);p.addProperty("total_orders",r.get("total_orders").getAsLong());money(p,"total_purchased",Money.of(r,"total_purchased"));p.addProperty("last_order",text(r,"last_order_date",""));parties.add(p);}JsonObject s=new JsonObject();s.addProperty("total_parties",parties.size());money(s,"total_credits",credits);money(s,"total_outstanding",outstanding);s.addProperty("parties_with_credit",withCredit);s.addProperty("parties_with_dues",withDues);JsonObject out=new JsonObject();out.add("parties",parties);out.add("summary",s);return out;}

    JsonObject taxLedger(String from,String to)throws SQLException,RpcException{requireDates(from,to);JsonArray rows=database.query("SELECT o.order_id,o.created_at,o.total,b.bill,u.name user_name FROM orders o LEFT JOIN bills b ON o.order_id=b.order_id LEFT JOIN userdata u ON o.user_id=u.uid OR o.user_id=u.id WHERE o.created_at>=? AND o.created_at<=? ORDER BY o.created_at",List.of(from+"T00:00:00",to+"T23:59:59"));Map<String,Rate>rates=new LinkedHashMap<>();JsonArray entries=new JsonArray();for(JsonElement x:rows){JsonObject r=x.getAsJsonObject(),b=bill(r);if(b==null)continue;for(JsonElement g:b.getAsJsonArray("gstDetails")){JsonObject d=g.getAsJsonObject();BigDecimal rate=new BigDecimal(text(d,"cgstRate","0").replace("%","")).multiply(new BigDecimal("2"));String key=rate.stripTrailingZeros().toPlainString()+"%";Rate sum=rates.computeIfAbsent(key,k->new Rate(rate));sum.add(d);JsonObject e=new JsonObject();e.addProperty("date",text(r,"created_at",""));e.addProperty("invoice",text(b.getAsJsonObject("details"),"invoiceNo","INV-"+text(r,"order_id","")));e.addProperty("party",text(r,"user_name",""));e.addProperty("hsn",text(d,"hsnSac",""));e.addProperty("rate",rate);money(e,"taxable",Money.of(d,"taxableValue"));money(e,"cgst",Money.of(d,"cgstAmount"));money(e,"sgst",Money.of(d,"sgstUtgstAmount"));money(e,"total_tax",Money.of(d,"totalTaxAmount"));entries.add(e);}}JsonObject summary=new JsonObject();BigDecimal taxable=Money.ZERO,tax=Money.ZERO;for(Map.Entry<String,Rate>e:rates.entrySet()){summary.add(e.getKey(),e.getValue().json());taxable=taxable.add(e.getValue().taxable);tax=tax.add(e.getValue().tax);}JsonObject totals=new JsonObject();money(totals,"total_taxable",taxable);money(totals,"total_tax",tax);JsonObject out=new JsonObject();out.add("rate_summary",summary);out.add("entries",entries);out.add("totals",totals);return out;}

    JsonObject dashboardExtras(String fy)throws SQLException,RpcException{Range range=financialYear(fy);JsonArray top=database.query("SELECT u.name,u.uid,COUNT(o.order_id) orders,COALESCE(SUM(CASE WHEN o.order_status!='ORDER_CANCELLED' THEN o.total ELSE 0 END),0) value FROM orders o JOIN userdata u ON o.user_id=u.uid OR o.user_id=u.id WHERE o.created_at>=? AND o.created_at<=? GROUP BY u.uid ORDER BY value DESC LIMIT 10",List.of(range.fromIso(),range.toIso()));JsonObject statuses=new JsonObject();for(JsonElement x:database.query("SELECT order_status,COUNT(*) count,COALESCE(SUM(total),0) value FROM orders WHERE created_at>=? AND created_at<=? GROUP BY order_status",List.of(range.fromIso(),range.toIso()))){JsonObject r=x.getAsJsonObject(),v=new JsonObject();v.addProperty("count",r.get("count").getAsLong());money(v,"value",Money.of(r,"value"));statuses.add(text(r,"order_status","Unknown"),v);}JsonArray recent=database.query("SELECT o.order_id,o.created_at date,o.total,o.order_status status,u.name party FROM orders o LEFT JOIN userdata u ON o.user_id=u.uid OR o.user_id=u.id WHERE o.created_at>=? AND o.created_at<=? ORDER BY o.created_at DESC LIMIT 10",List.of(range.fromIso(),range.toIso()));JsonObject out=new JsonObject();out.add("top_customers",top);out.add("status_distribution",statuses);out.add("recent_activity",recent);return out;}

    private void addNoteLedger(JsonArray entries,String table,String number,String type,String from,String to,String user,boolean debit)throws SQLException{String filter=user==null?"":" AND user_id=?";List<Object>p=new ArrayList<>(List.of(from+"T00:00:00",to+"T23:59:59"));if(user!=null)p.add(user);for(JsonElement x:database.query("SELECT * FROM "+table+" WHERE created_at>=? AND created_at<=?"+filter+" ORDER BY created_at",p)){JsonObject r=x.getAsJsonObject();entries.add(ledger(r,type,text(r,number,""),debit?Money.of(r,"total"):Money.ZERO,debit?Money.ZERO:Money.of(r,"total")));}}
    private static JsonObject ledger(JsonObject r,String type,String voucher,BigDecimal debit,BigDecimal credit){JsonObject e=new JsonObject();e.addProperty("date",text(r,"created_at",""));e.addProperty("type",type);e.addProperty("voucher_no",voucher);e.addProperty("party_name",text(r,"user_name",""));money(e,"debit",debit);money(e,"credit",credit);return e;}
    private void addDayNotes(JsonArray entries,String table,String number,String type,String from,String to)throws SQLException{for(JsonElement x:database.query("SELECT * FROM "+table+" WHERE created_at>=? AND created_at<=? ORDER BY created_at",List.of(from+"T00:00:00",to+"T23:59:59"))){JsonObject r=x.getAsJsonObject(),e=new JsonObject();e.addProperty("date",text(r,"created_at",""));e.addProperty("type",type);e.addProperty("voucher_no",text(r,number,""));e.addProperty("party",text(r,"user_name",text(r,"user_id","")));money(e,"amount",Money.of(r,"total"));money(e,"taxable",Money.of(r,"subtotal"));money(e,"tax",Money.of(r,"cgst_total").add(Money.of(r,"sgst_total")));e.addProperty("status","Issued");e.addProperty("order_id",text(r,"original_invoice",""));entries.add(e);}}
    private JsonObject noteTotals(String table,Range range)throws SQLException{return database.one("SELECT COALESCE(SUM(total),0) total,COALESCE(SUM(subtotal),0) subtotal,COALESCE(SUM(cgst_total),0) cgst,COALESCE(SUM(sgst_total),0) sgst FROM "+table+" WHERE created_at>=? AND created_at<=?",List.of(range.fromIso(),range.toIso()));}
    private static JsonObject bill(JsonObject row){if(!row.has("bill")||row.get("bill").isJsonNull())return null;try{return JsonParser.parseString(row.get("bill").getAsString()).getAsJsonObject();}catch(RuntimeException e){return null;}}
    private static String text(JsonObject o,String k,String fallback){JsonElement v=o==null?null:o.get(k);return v==null||v.isJsonNull()?fallback:v.getAsString();}
    private static void money(JsonObject o,String k,BigDecimal v){o.addProperty(k,Money.output(v));}
    private static void sort(JsonArray array,String field){List<JsonElement>v=new ArrayList<>();array.forEach(v::add);v.sort(Comparator.comparing(x->text(x.getAsJsonObject(),field,"")));while(!array.isEmpty())array.remove(0);v.forEach(array::add);}
    private static int digits(String input){String d=input.replaceAll("\\D","");return d.isEmpty()?0:Integer.parseInt(d);}
    private static void requireDates(String from,String to)throws RpcException{if(from==null||to==null)throw new RpcException("INVALID_REQUEST","from_date and to_date are required");try{LocalDate.parse(from);LocalDate.parse(to);}catch(RuntimeException e){throw new RpcException("INVALID_REQUEST","Dates must use YYYY-MM-DD",e);}}
    private static Range financialYear(String fy)throws RpcException{int start;LocalDate now=LocalDate.now(ZoneOffset.UTC);if(fy!=null&&fy.contains("-")){try{start=Integer.parseInt(fy.split("-")[0]);}catch(RuntimeException e){throw new RpcException("INVALID_REQUEST","fy must look like 2025-26",e);}}else start=now.getMonthValue()>=4?now.getYear():now.getYear()-1;return new Range(LocalDate.of(start,4,1).toString(),LocalDate.of(start+1,3,31).toString());}
    private static final class Range{final String from,to;Range(String f,String t){from=f;to=t;}String fromIso(){return from+"T00:00:00";}String toIso(){return to+"T23:59:59";}}
    private static final class Totals{BigDecimal taxable=Money.ZERO,cgst=Money.ZERO,sgst=Money.ZERO,total=Money.ZERO;int count;void add(BigDecimal a,BigDecimal b,BigDecimal c,BigDecimal d){taxable=taxable.add(a);cgst=cgst.add(b);sgst=sgst.add(c);total=total.add(d);count++;}JsonObject json(){JsonObject o=new JsonObject();money(o,"taxable",taxable);money(o,"cgst",cgst);money(o,"sgst",sgst);money(o,"total",total);o.addProperty("count",count);return o;}}
    private static final class Category{int count;long stock;BigDecimal value=Money.ZERO;void add(int s,BigDecimal v){count++;stock+=s;value=value.add(v);}JsonObject json(){JsonObject o=new JsonObject();o.addProperty("count",count);o.addProperty("stock",stock);money(o,"value",value);return o;}}
    private static final class Rate{final BigDecimal rate;BigDecimal taxable=Money.ZERO,cgst=Money.ZERO,sgst=Money.ZERO,tax=Money.ZERO;int invoices;Rate(BigDecimal r){rate=r;}void add(JsonObject d){taxable=taxable.add(Money.of(d,"taxableValue"));cgst=cgst.add(Money.of(d,"cgstAmount"));sgst=sgst.add(Money.of(d,"sgstUtgstAmount"));tax=tax.add(Money.of(d,"totalTaxAmount"));invoices++;}JsonObject json(){JsonObject o=new JsonObject();o.addProperty("rate",rate);money(o,"taxable",taxable);money(o,"cgst",cgst);money(o,"sgst",sgst);money(o,"total_tax",tax);o.addProperty("invoices",invoices);return o;}}
}
