package in.petsfort.crm;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.lang.management.ManagementFactory;
import java.lang.management.MemoryUsage;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.nio.file.FileStore;
import java.nio.file.FileSystems;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

final class SystemMetrics {
    private SystemMetrics() {}

    static JsonObject snapshot() {
        Runtime runtime=Runtime.getRuntime();com.sun.management.OperatingSystemMXBean os=(com.sun.management.OperatingSystemMXBean)ManagementFactory.getOperatingSystemMXBean();JsonObject root=new JsonObject();root.addProperty("timestamp",Instant.now().toEpochMilli()/1000.0);
        JsonObject cpu=new JsonObject();cpu.addProperty("logical_cores",runtime.availableProcessors());cpu.addProperty("physical_cores",runtime.availableProcessors());double load=os.getSystemCpuLoad()*100;cpu.addProperty("total_cpu_usage_percent",load<0?0:load);JsonArray per=new JsonArray();for(int i=0;i<runtime.availableProcessors();i++)per.add(load<0?0:load);cpu.add("usage_percent_per_cpu",per);JsonObject times=new JsonObject();for(String key:List.of("user","system","idle","nice","iowait","irq","softirq","steal","guest","guest_nice"))times.addProperty(key,"N/A");cpu.add("times",times);JsonObject stats=new JsonObject();for(String key:List.of("ctx_switches","interrupts","soft_interrupts","syscalls"))stats.addProperty(key,"N/A");cpu.add("stats",stats);cpu.addProperty("frequency","N/A");JsonObject loads=new JsonObject();loads.addProperty("1_min",os.getSystemLoadAverage());loads.addProperty("5_min",os.getSystemLoadAverage());loads.addProperty("15_min",os.getSystemLoadAverage());cpu.add("load_average",loads);root.add("cpu",cpu);
        JsonObject memory=new JsonObject(),virtual=new JsonObject();long total=os.getTotalPhysicalMemorySize(),free=os.getFreePhysicalMemorySize(),used=total-free;virtual.addProperty("total_gb",gb(total));virtual.addProperty("available_gb",gb(free));virtual.addProperty("used_gb",gb(used));virtual.addProperty("free_gb",gb(free));virtual.addProperty("percent_used",total==0?0:used*100.0/total);for(String key:List.of("active_gb","inactive_gb","buffers_gb","cached_gb","shared_gb","slab_gb"))virtual.addProperty(key,0);memory.add("virtual_memory",virtual);JsonObject swap=new JsonObject();long st=os.getTotalSwapSpaceSize(),sf=os.getFreeSwapSpaceSize();swap.addProperty("total_gb",gb(st));swap.addProperty("used_gb",gb(st-sf));swap.addProperty("free_gb",gb(sf));swap.addProperty("percent_used",st==0?0:(st-sf)*100.0/st);swap.addProperty("sin_gb",0);swap.addProperty("sout_gb",0);memory.add("swap_memory",swap);root.add("memory",memory);
        JsonObject disk=new JsonObject();JsonArray partitions=new JsonArray();for(FileStore store:FileSystems.getDefault().getFileStores())try{JsonObject p=new JsonObject();p.addProperty("device",store.name());p.addProperty("mountpoint",store.toString());p.addProperty("fstype",store.type());p.addProperty("opts","");p.addProperty("total_gb",gb(store.getTotalSpace()));p.addProperty("used_gb",gb(store.getTotalSpace()-store.getUsableSpace()));p.addProperty("free_gb",gb(store.getUsableSpace()));p.addProperty("percent_used",store.getTotalSpace()==0?0:(store.getTotalSpace()-store.getUsableSpace())*100.0/store.getTotalSpace());partitions.add(p);}catch(Exception ignored){}disk.add("partitions",partitions);JsonObject diskIo=new JsonObject();for(String key:List.of("read_count","write_count","read_bytes_gb","write_bytes_gb","read_time_ms","write_time_ms","read_merged_count","write_merged_count","busy_time_ms"))diskIo.addProperty(key,"N/A");disk.add("io_counters",diskIo);root.add("disk",disk);
        JsonObject network=new JsonObject(),interfaces=new JsonObject();try{for(NetworkInterface ni:Collections.list(NetworkInterface.getNetworkInterfaces())){JsonObject entry=new JsonObject();JsonArray addresses=new JsonArray();for(InetAddress address:Collections.list(ni.getInetAddresses())){JsonObject a=new JsonObject();a.addProperty("family",address.getClass().getSimpleName());a.addProperty("address",address.getHostAddress());a.addProperty("netmask","N/A");a.addProperty("broadcast","N/A");a.addProperty("ptp","N/A");addresses.add(a);}entry.add("addresses",addresses);JsonObject ifStats=new JsonObject();ifStats.addProperty("is_up",ni.isUp());ifStats.addProperty("duplex","N/A");ifStats.addProperty("speed_mbps","N/A");ifStats.addProperty("mtu_bytes",ni.getMTU());entry.add("stats",ifStats);interfaces.add(ni.getName(),entry);}}catch(Exception ignored){}JsonObject netIo=new JsonObject();for(String key:List.of("bytes_sent_gb","bytes_recv_gb","packets_sent","packets_recv","errin","errout","dropin","dropout"))netIo.addProperty(key,0);network.add("io_counters",netIo);network.add("interfaces",interfaces);network.addProperty("connections_count","N/A");network.add("connections_sample",new JsonArray());root.add("network",network);
        JsonObject system=new JsonObject();long bootMillis=System.currentTimeMillis()-ManagementFactory.getRuntimeMXBean().getUptime();system.addProperty("boot_time_timestamp",bootMillis/1000.0);system.addProperty("boot_time_readable",DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").withZone(ZoneId.systemDefault()).format(Instant.ofEpochMilli(bootMillis)));system.add("users",new JsonArray());JsonObject platform=new JsonObject();platform.addProperty("system",System.getProperty("os.name"));platform.addProperty("node_hostname",hostname());platform.addProperty("release",System.getProperty("os.version"));platform.addProperty("version",System.getProperty("os.version"));platform.addProperty("machine_arch",System.getProperty("os.arch"));platform.addProperty("processor",System.getProperty("os.arch"));platform.addProperty("python_version","N/A (Java server)");platform.addProperty("os_name",System.getProperty("os.name"));system.add("platform_details",platform);root.add("system_os",system);
        JsonObject processes=new JsonObject();List<ProcessHandle>all=new ArrayList<>();ProcessHandle.allProcesses().forEach(all::add);processes.addProperty("total_processes",all.size());JsonArray sample=new JsonArray();all.stream().limit(5).forEach(process->{JsonObject p=new JsonObject();p.addProperty("pid",process.pid());p.addProperty("name",process.info().command().orElse("N/A"));p.addProperty("cpu_percent",0);p.addProperty("memory_percent",0);p.addProperty("status",process.isAlive()?"running":"stopped");p.addProperty("username",process.info().user().orElse("N/A"));sample.add(p);});processes.add("top_processes_by_memory",sample);processes.add("top_processes_by_cpu",sample.deepCopy());root.add("processes_summary",processes);JsonObject sensors=new JsonObject();sensors.addProperty("temperatures","Not available or not supported");sensors.addProperty("fans","Not available or not supported");sensors.addProperty("battery","Not available or not supported");root.add("sensors",sensors);return root;
    }

    static String freeCommand(){try{Process process=new ProcessBuilder("free","-h").start();try(BufferedReader reader=new BufferedReader(new InputStreamReader(process.getInputStream()))){StringBuilder out=new StringBuilder();String line;while((line=reader.readLine())!=null)out.append(line).append('\n');return out.toString();}}catch(Exception e){return "Memory command unavailable: "+e.getMessage();}}
    private static double gb(long bytes){return Math.round(bytes/1073741824.0*100.0)/100.0;}
    private static String hostname(){try{return InetAddress.getLocalHost().getHostName();}catch(Exception e){return "unknown";}}
}
