# fly.toml app configuration file generated for jay-fastapi on 2025-06-01T15:15:31+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jay-fastapi'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'sqlite_data'
  destination = '/app/sqlite'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
